export const ADD_BOOK_TO_CART = 'ADD_BOOK_TO_CART'
export const REMOVE_BOOK_FROM_CART = 'REMOVE_BOOK_FROM_CART'
export const ADD_MAGAZINE_TO_CART = 'ADD_MAGAZINE_TO_CART'
export const REMOVE_MAGAZINE_FROM_CART = 'REMOVE_MAGAZINE_FROM_CART'